# Generated by Django 3.2.15 on 2022-09-21 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_dexc',
            new_name='item_desc',
        ),
    ]
